version: '3.7'
services:
  front:
    stdin_open: true
    tty: true
    build: ./front/
    ports:
      - "80:80"
    volumes:
      - "./front/app/:/data/app/"
      - "./front/scripts:/data/scripts"
    command: bash -c "/data/scripts/start.sh"
    networks:
        tars_net:
          ipv4_address: 172.16.0.10
          ipv6_address: 2001:3984:3989::10
  db:
    build: ./db
    ports:
      - "27017:27017"
    volumes:
      - "./db/data:/data/db"
    networks:
        tars_net:
          ipv4_address: 172.16.0.12
          ipv6_address: 2001:3984:3979::10

networks:
  tars_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: "172.16.0.0/24"
      - subnet: "2001:3984:3989::/64"
