version: '3.7'
services:
  db:
    build: ./db
    ports:
      - "27017:27017"
    volumes:
      - "./db/data:/data/db"
    logging:
      driver: none
    networks:
        tars_net:
          ipv4_address: 172.16.0.12
          ipv6_address: 2001:3984:3979::10
  messaging:
    build: ./messaging
    ports:
      - "5672:5672"
    volumes:
      - "./messaging/data:/data/messaging"
    logging:
      driver: none
    networks:
        tars_net:
          ipv4_address: 172.16.0.15
          ipv6_address: 2001:3984:4019::10
  user:
    stdin_open: true
    tty: true
    build: ./services/user
    volumes:
          - "./services/user/:/data/app/"
          - "./services/config/:/data/app/src/config"
          - "./services/base/:/data/app/src/base"
    depends_on:
      - "db"
      - "messaging"
    ports:
      - "3001:3001"
    networks:
        tars_net:
          ipv4_address: 172.16.0.14
          ipv6_address: 2001:3984:3999::10
  gateway:
    stdin_open: true
    #tty: true
    build: ./services/gateway
    volumes:
          - "./services/gateway/:/data/app/"
          - "./services/config/:/data/app/src/config"
          - "./services/base/:/data/app/src/base"
    depends_on:
      - "user"
    ports:
      - "3000:3000"
    networks:
        tars_net:
          ipv4_address: 172.16.0.13
          ipv6_address: 2001:3984:4009::10
  front:
    stdin_open: true
    tty: true
    build: ./front/
    depends_on:
      - "gateway"
    ports:
      - "80:80"
    volumes:
      - "./front/app/:/data/app/"
      - "./front/scripts:/data/scripts"
    command: bash -c "/data/scripts/start.sh"
    networks:
        tars_net:
          ipv4_address: 172.16.0.10
          ipv6_address: 2001:3984:3989::10

networks:
  tars_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: "172.16.0.0/24"
      - subnet: "2001:3984:3989::/64"
